package tfg.app.controller;

import java.time.LocalDate;
import java.util.List;

import javax.swing.tree.DefaultMutableTreeNode;

import tfg.app.model.entities.FundDesc;
import tfg.app.model.entities.FundPort;
import tfg.app.model.entities.FundVl;
import tfg.app.model.service.FundService;
import tfg.app.model.service.FundServiceImpl;
import tfg.app.util.exceptions.InputValidationException;
import tfg.app.util.exceptions.InstanceNotFoundException;

/**
 *
 * @author angel
 */
@SuppressWarnings("serial")
public class ui extends javax.swing.JFrame {

	/**
	 * Creates new form Pruebas
	 */
	public ui() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		anadirFondo = new javax.swing.JDialog();
		isinLabel = new javax.swing.JLabel();
		isinText = new javax.swing.JTextField();
		gestoraText = new javax.swing.JTextField();
		tipoText = new javax.swing.JTextField();
		categoriaText = new javax.swing.JTextField();
		divisaText = new javax.swing.JTextField();
		gestoraLabel = new javax.swing.JLabel();
		tipoLabel = new javax.swing.JLabel();
		categoriaLabel = new javax.swing.JLabel();
		divisaLabel = new javax.swing.JLabel();
		apComLabel = new javax.swing.JLabel();
		cancelComLabel = new javax.swing.JLabel();
		canAnaFondoBoton = new javax.swing.JButton();
		anadFondoBoton = new javax.swing.JButton();
		cancelComText = new javax.swing.JFormattedTextField();
		apComText = new javax.swing.JFormattedTextField();
		anadirCartera = new javax.swing.JDialog();
		nomCarteraLabel = new javax.swing.JLabel();
		nomCarteraText = new javax.swing.JTextField();
		descCarteraLabel = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		descCarteraText = new javax.swing.JTextArea();
		canAnaCarteraBoton = new javax.swing.JButton();
		anaCarteraBoton = new javax.swing.JButton();
		anadirVl = new javax.swing.JDialog();
		vlIsinLabel = new javax.swing.JLabel();
		vlIsinIdLabel = new javax.swing.JLabel();
		vlFechaLabel = new javax.swing.JLabel();
		vlVlLabel = new javax.swing.JLabel();
		vlVlText = new javax.swing.JFormattedTextField();
		vlCancBoton = new javax.swing.JButton();
		vlAccBoton = new javax.swing.JButton();
		vlFechaText = new javax.swing.JSpinner();
		anadirOp = new javax.swing.JDialog();
		opIsinLabel = new javax.swing.JLabel();
		opCarteraLabel = new javax.swing.JLabel();
		opFechaLabel = new javax.swing.JLabel();
		opOperacionLabel = new javax.swing.JLabel();
		opOperacionText = new javax.swing.JFormattedTextField();
		opCancBoton = new javax.swing.JButton();
		opAccBoton = new javax.swing.JButton();
		opFechaText = new javax.swing.JSpinner();
		vlMenu = new javax.swing.JPopupMenu();
		actuVl = new javax.swing.JMenuItem();
		borrarVl = new javax.swing.JMenuItem();
		fondoMenu = new javax.swing.JPopupMenu();
		anadVlaFondo = new javax.swing.JMenuItem();
		actualizarFondo = new javax.swing.JMenuItem();
		borrarFondo = new javax.swing.JMenuItem();
		carteraMenu = new javax.swing.JPopupMenu();
		anFondoAcartera = new javax.swing.JMenuItem();
		actualizarCartera = new javax.swing.JMenuItem();
		borrarCartera = new javax.swing.JMenuItem();
		buscarText = new javax.swing.JTextField();
		buscarLabel = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		DefaultMutableTreeNode top = new DefaultMutableTreeNode("Carteras");
		createNodes(top);
		arbolFondos = new javax.swing.JTree(top);
		barraMenu = new javax.swing.JMenuBar();
		jMenu3 = new javax.swing.JMenu();
		jMenu1 = new javax.swing.JMenu();
		botonAnadirFondo = new javax.swing.JMenuItem();
		botonAnadirCartera = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();

		anadirFondo.setTitle("Añadir Fondo");
		anadirFondo.setAlwaysOnTop(true);
		anadirFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		anadirFondo.setLocation(new java.awt.Point(0, 0));
		anadirFondo.setLocationByPlatform(true);
		anadirFondo.setModal(true);
		anadirFondo.setResizable(false);
		anadirFondo.setSize(new java.awt.Dimension(360, 350));

		isinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		isinLabel.setText("ISIN:");

		gestoraLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		gestoraLabel.setText("Gestora:");

		tipoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		tipoLabel.setText("Tipo:");

		categoriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		categoriaLabel.setText("Categoría:");

		divisaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		divisaLabel.setText("Divisa:");

		apComLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		apComLabel.setText("Comision de apertura:");

		cancelComLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		cancelComLabel.setText("Comisión de cancelación:");

		canAnaFondoBoton.setText("Cancelar");
		canAnaFondoBoton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				canAnaFondoBotonActionPerformed(evt);
			}
		});

		anadFondoBoton.setText("Aceptar");
		anadFondoBoton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				anadFondoBotonActionPerformed(evt);
			}
		});

		cancelComText.setValue(new Integer(0));

		apComText.setValue(new Integer(0));

		javax.swing.GroupLayout anadirFondoLayout = new javax.swing.GroupLayout(anadirFondo.getContentPane());
		anadirFondo.getContentPane().setLayout(anadirFondoLayout);
		anadirFondoLayout.setHorizontalGroup(anadirFondoLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						anadirFondoLayout.createSequentialGroup().addContainerGap().addGroup(anadirFondoLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(isinLabel)
								.addComponent(gestoraLabel).addComponent(tipoLabel).addComponent(categoriaLabel)
								.addComponent(divisaLabel).addComponent(cancelComLabel).addComponent(apComLabel))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(
										anadirFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(divisaText, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 122,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(cancelComText, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 139,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(categoriaText, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 122,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(tipoText, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 122,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(gestoraText, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 122,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(isinText, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 122,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(apComText, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 139,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap())
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						anadirFondoLayout.createSequentialGroup().addContainerGap(158, Short.MAX_VALUE)
								.addComponent(canAnaFondoBoton).addGap(18, 18, 18).addComponent(anadFondoBoton)
								.addGap(15, 15, 15)));

		anadirFondoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { apComLabel,
				cancelComLabel, categoriaLabel, divisaLabel, gestoraLabel, isinLabel, tipoLabel });

		anadirFondoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { cancelComText, categoriaText, divisaText, gestoraText, isinText, tipoText });

		anadirFondoLayout.setVerticalGroup(anadirFondoLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(anadirFondoLayout.createSequentialGroup().addGap(23, 23, 23)
						.addGroup(anadirFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(isinLabel).addComponent(isinText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(anadirFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(gestoraLabel).addComponent(gestoraText,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(anadirFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(tipoText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(tipoLabel))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(anadirFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(categoriaText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(categoriaLabel))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(anadirFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(divisaText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(divisaLabel))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(anadirFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(apComLabel).addComponent(apComText,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(anadirFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(cancelComLabel).addComponent(cancelComText,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(anadirFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(anadFondoBoton).addComponent(canAnaFondoBoton))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		anadirFondoLayout.linkSize(javax.swing.SwingConstants.VERTICAL,
				new java.awt.Component[] { isinLabel, isinText });

		anadirFondoLayout.linkSize(javax.swing.SwingConstants.VERTICAL,
				new java.awt.Component[] { apComLabel, cancelComLabel, categoriaLabel, categoriaText, divisaLabel,
						divisaText, gestoraLabel, gestoraText, tipoLabel, tipoText });

		anadirCartera.setTitle("Añadir Cartera");
		anadirCartera.setAlwaysOnTop(true);
		anadirCartera.setModal(true);
		anadirCartera.setResizable(false);
		anadirCartera.setSize(new java.awt.Dimension(380, 280));

		nomCarteraLabel.setText("Nombre de la cartera:");

		descCarteraLabel.setText("Descripcción:");

		descCarteraText.setColumns(20);
		descCarteraText.setRows(5);
		jScrollPane1.setViewportView(descCarteraText);

		canAnaCarteraBoton.setText("Cancelar");
		canAnaCarteraBoton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				canAnaCarteraBotonActionPerformed(evt);
			}
		});

		anaCarteraBoton.setText("Aceptar");
		anaCarteraBoton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				anaCarteraBotonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout anadirCarteraLayout = new javax.swing.GroupLayout(anadirCartera.getContentPane());
		anadirCartera.getContentPane().setLayout(anadirCarteraLayout);
		anadirCarteraLayout.setHorizontalGroup(
				anadirCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						anadirCarteraLayout
								.createSequentialGroup().addContainerGap()
								.addGroup(anadirCarteraLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anadirCarteraLayout
												.createSequentialGroup()
												.addGroup(anadirCarteraLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(descCarteraLabel).addComponent(nomCarteraLabel))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29,
														Short.MAX_VALUE)
												.addGroup(anadirCarteraLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jScrollPane1).addComponent(nomCarteraText)))
										.addGroup(anadirCarteraLayout.createSequentialGroup()
												.addGap(0, 0, Short.MAX_VALUE).addComponent(canAnaCarteraBoton)
												.addGap(18, 18, 18).addComponent(anaCarteraBoton)))
								.addContainerGap()));

		anadirCarteraLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { anaCarteraBoton, canAnaCarteraBoton });

		anadirCarteraLayout.setVerticalGroup(anadirCarteraLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(anadirCarteraLayout.createSequentialGroup().addGap(38, 38, 38)
						.addGroup(anadirCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(nomCarteraLabel).addComponent(nomCarteraText,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(anadirCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(descCarteraLabel).addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
						.addGroup(anadirCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(canAnaCarteraBoton).addComponent(anaCarteraBoton))
						.addContainerGap()));

		anadirCarteraLayout.linkSize(javax.swing.SwingConstants.VERTICAL,
				new java.awt.Component[] { nomCarteraLabel, nomCarteraText });

		anadirVl.setTitle("Añadir VL");
		anadirVl.setAlwaysOnTop(true);
		anadirVl.setModal(true);
		anadirVl.setSize(new java.awt.Dimension(400, 260));

		vlIsinLabel.setText("ISIN:");

		vlIsinIdLabel.setText("ISIN ID");

		vlFechaLabel.setText("Fecha:");

		vlVlLabel.setText("Valor liquidativo:");

		vlVlText.setFormatterFactory(
				new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
		vlVlText.setValue(new Integer(0));

		vlCancBoton.setText("Cancelar");

		vlAccBoton.setText("Aceptar");

		vlFechaText.setModel(new javax.swing.SpinnerDateModel());
		vlFechaText.setEditor(new javax.swing.JSpinner.DateEditor(vlFechaText, "yyyy-MM-dd"));

		javax.swing.GroupLayout anadirVlLayout = new javax.swing.GroupLayout(anadirVl.getContentPane());
		anadirVl.getContentPane().setLayout(anadirVlLayout);
		anadirVlLayout
				.setHorizontalGroup(anadirVlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(anadirVlLayout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(anadirVlLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(vlIsinIdLabel).addGroup(anadirVlLayout
												.createSequentialGroup()
												.addGroup(anadirVlLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(anadirVlLayout.createSequentialGroup()
																.addComponent(vlCancBoton)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(vlAccBoton))
														.addGroup(anadirVlLayout.createSequentialGroup()
																.addGroup(anadirVlLayout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(vlFechaLabel,
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGroup(anadirVlLayout.createSequentialGroup()
																				.addComponent(vlVlLabel).addGap(15, 15,
																						15))
																		.addComponent(vlIsinLabel,
																				javax.swing.GroupLayout.Alignment.TRAILING))
																.addGap(33, 33, 33)
																.addGroup(anadirVlLayout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(vlFechaText,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(vlVlText))))
												.addGap(22, 22, 22)))
								.addContainerGap()));

		anadirVlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { vlFechaLabel,
				vlFechaText, vlIsinIdLabel, vlIsinLabel, vlVlLabel, vlVlText });

		anadirVlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { vlAccBoton, vlCancBoton });

		anadirVlLayout.setVerticalGroup(anadirVlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(anadirVlLayout.createSequentialGroup().addGap(25, 25, 25)
						.addGroup(anadirVlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(vlIsinLabel, javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(vlIsinIdLabel))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(anadirVlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(vlFechaLabel).addComponent(vlFechaText,
										javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(anadirVlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(vlVlLabel).addComponent(vlVlText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(anadirVlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(vlCancBoton).addComponent(vlAccBoton))
						.addContainerGap(92, Short.MAX_VALUE)));

		anadirVlLayout.linkSize(javax.swing.SwingConstants.VERTICAL,
				new java.awt.Component[] { vlFechaLabel, vlIsinIdLabel, vlIsinLabel, vlVlLabel, vlVlText });

		anadirVlLayout.linkSize(javax.swing.SwingConstants.VERTICAL,
				new java.awt.Component[] { vlAccBoton, vlCancBoton });

		anadirOp.setTitle("Añadir Operación");
		anadirOp.setAlwaysOnTop(true);
		anadirOp.setModal(true);
		anadirOp.setSize(new java.awt.Dimension(420, 260));

		opIsinLabel.setText("ISIN ID");

		opCarteraLabel.setText("Nomb Cart");

		opFechaLabel.setText("Fecha:");

		opOperacionLabel.setText("Participaciones(+/-):");

		opOperacionText.setFormatterFactory(
				new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
		opOperacionText.setValue(new Integer(0));

		opCancBoton.setText("Cancelar");

		opAccBoton.setText("Aceptar");

		opFechaText.setModel(new javax.swing.SpinnerDateModel());
		opFechaText.setEditor(new javax.swing.JSpinner.DateEditor(vlFechaText, "yyyy-MM-dd"));

		javax.swing.GroupLayout anadirOpLayout = new javax.swing.GroupLayout(anadirOp.getContentPane());
		anadirOp.getContentPane().setLayout(anadirOpLayout);
		anadirOpLayout
				.setHorizontalGroup(
						anadirOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(anadirOpLayout.createSequentialGroup().addGap(36, 36, 36).addGroup(
										anadirOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(anadirOpLayout
														.createSequentialGroup().addComponent(opCancBoton)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(opAccBoton))
												.addGroup(anadirOpLayout
														.createSequentialGroup().addGroup(
																anadirOpLayout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(opFechaLabel,
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				161,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGroup(anadirOpLayout.createSequentialGroup()
																				.addGroup(anadirOpLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(opOperacionLabel)
																						.addComponent(opIsinLabel))
																				.addGap(15, 15, 15)))
														.addGap(33, 33, 33)
														.addGroup(anadirOpLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(anadirOpLayout.createSequentialGroup()
																		.addComponent(opCarteraLabel).addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				71, Short.MAX_VALUE))
																.addComponent(opOperacionText)
																.addComponent(opFechaText))))
										.addGap(22, 22, 22)));
		anadirOpLayout.setVerticalGroup(anadirOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(anadirOpLayout.createSequentialGroup().addGap(25, 25, 25)
						.addGroup(anadirOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(opIsinLabel, javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(opCarteraLabel))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(anadirOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(opFechaLabel).addComponent(opFechaText,
										javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(anadirOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(opOperacionLabel).addComponent(opOperacionText,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(anadirOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(opCancBoton).addComponent(opAccBoton))
						.addContainerGap(75, Short.MAX_VALUE)));

		actuVl.setText("Actualizar");
		actuVl.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				actuVlActionPerformed(evt);
			}
		});
		vlMenu.add(actuVl);

		borrarVl.setText("Borrar");
		borrarVl.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				borrarVlActionPerformed(evt);
			}
		});
		vlMenu.add(borrarVl);

		anadVlaFondo.setText("Añadir VL");
		anadVlaFondo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				anadVlaFondoActionPerformed(evt);
			}
		});
		fondoMenu.add(anadVlaFondo);

		actualizarFondo.setText("Actualizar");
		actualizarFondo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				actualizarFondoActionPerformed(evt);
			}
		});
		fondoMenu.add(actualizarFondo);

		borrarFondo.setText("Borrar");
		borrarFondo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				borrarFondoActionPerformed(evt);
			}
		});
		fondoMenu.add(borrarFondo);

		anFondoAcartera.setText("Añadir Fondo");
		anFondoAcartera.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				anFondoAcarteraActionPerformed(evt);
			}
		});
		carteraMenu.add(anFondoAcartera);

		actualizarCartera.setText("Actualizar");
		actualizarCartera.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				actualizarCarteraActionPerformed(evt);
			}
		});
		carteraMenu.add(actualizarCartera);

		borrarCartera.setText("Borrar");
		borrarCartera.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				borrarCarteraActionPerformed(evt);
			}
		});
		carteraMenu.add(borrarCartera);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Aplicación");
		setName("Ventana Principal"); // NOI18N

		buscarText.setText("Buscar");

		buscarLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("../util/images/buscar.png"))); // NOI18N

		arbolFondos.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				arbolFondosMousePressed(evt);
			}

			public void mouseReleased(java.awt.event.MouseEvent evt) {
				arbolFondosMouseReleased(evt);
			}
		});
		arbolFondos.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
			public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
				arbolFondosValueChanged(evt);
			}
		});
		jScrollPane2.setViewportView(arbolFondos);

		jMenu3.setText("Archivo");

		jMenu1.setText("Añadir");

		botonAnadirFondo.setText("Fondo");
		botonAnadirFondo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonAnadirFondoActionPerformed(evt);
			}
		});
		jMenu1.add(botonAnadirFondo);

		botonAnadirCartera.setText("Cartera");
		botonAnadirCartera.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonAnadirCarteraActionPerformed(evt);
			}
		});
		jMenu1.add(botonAnadirCartera);

		jMenu3.add(jMenu1);

		barraMenu.add(jMenu3);

		jMenu4.setText("Editar");
		barraMenu.add(jMenu4);

		setJMenuBar(barraMenu);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addComponent(buscarText)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(buscarLabel)))
						.addContainerGap(789, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(buscarText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(buscarLabel))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
						.addContainerGap()));

		layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] { buscarLabel, buscarText });

		pack();
	}// </editor-fold>

	// Click en el boton de añadir fondo del menu archivo -> añadir
	private void botonAnadirFondoActionPerformed(java.awt.event.ActionEvent evt) {

		isinText.setText("");
		gestoraText.setText("");
		tipoText.setText("");
		categoriaText.setText("");
		cancelComText.setValue(0);
		apComText.setValue(0);
		divisaText.setText("");
		cancelComText.setText("");

		anadirFondo.setVisible(true);

	}

	// Click en el boton aceptar de la ventana de añadir fondo
	private void anadFondoBotonActionPerformed(java.awt.event.ActionEvent evt) {

		FundDesc fund = new FundDesc(isinText.getText(), gestoraText.getText(), tipoText.getText(),
				categoriaText.getText(), divisaText.getText(), Double.valueOf(apComText.getValue().toString()),
				Double.valueOf(cancelComText.getValue().toString()));

		try {
			fundService.addFund(fund);
		} catch (InputValidationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		anadirFondo.setVisible(false);

	}

	// Click en el boton cancelar de la ventana de añadir fondo
	private void canAnaFondoBotonActionPerformed(java.awt.event.ActionEvent evt) {

		anadirFondo.setVisible(false);

	}

	// Click en el boton de añadir cartera del menu archivo -> añadir
	private void botonAnadirCarteraActionPerformed(java.awt.event.ActionEvent evt) {

		descCarteraText.setText("");
		nomCarteraText.setText("");
		anadirCartera.setVisible(true);

	}

	// Click en el boton cancelar de la ventana de añadir cartera
	private void canAnaCarteraBotonActionPerformed(java.awt.event.ActionEvent evt) {

		anadirCartera.setVisible(false);

	}

	// Click en el boton añadir de la ventana de añadir cartera
	private void anaCarteraBotonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Seleccionar un elemento del árbol
	private void arbolFondosValueChanged(javax.swing.event.TreeSelectionEvent evt) {

		DefaultMutableTreeNode node = (DefaultMutableTreeNode) arbolFondos.getLastSelectedPathComponent();

		if (node == null)
			// Nothing is selected.
			return;

		// Object nodeInfo = node.getUserObject();
		// System.out.println(nodeInfo.getClass());
	}

	// Popupmenu en el arbol
	private void arbolFondosMousePressed(java.awt.event.MouseEvent evt) {

		if (evt.isPopupTrigger()) {

			DefaultMutableTreeNode node = (DefaultMutableTreeNode) arbolFondos.getLastSelectedPathComponent();
			Object nodeInfo = node.getUserObject();

			if (nodeInfo.getClass() == tfg.app.model.entities.FundDesc.class) {
				fondoMenu.show(this, evt.getX(), evt.getY());
			}
			if (nodeInfo.getClass() == tfg.app.model.entities.FundVl.class) {
				vlMenu.show(this, evt.getX(), evt.getY());
			}
			if (nodeInfo.getClass() == tfg.app.model.entities.FundPort.class) {
				carteraMenu.show(this, evt.getX(), evt.getY());
			}

		}
	}

	// Popupmenu en el arbol
	private void arbolFondosMouseReleased(java.awt.event.MouseEvent evt) {

		if (evt.isPopupTrigger()) {

			DefaultMutableTreeNode node = (DefaultMutableTreeNode) arbolFondos.getLastSelectedPathComponent();
			Object nodeInfo = node.getUserObject();

			if (nodeInfo.getClass() == tfg.app.model.entities.FundDesc.class) {
				fondoMenu.show(this, evt.getX(), evt.getY());
				return;
			}
			if (nodeInfo.getClass() == tfg.app.model.entities.FundVl.class) {
				vlMenu.show(this, evt.getX(), evt.getY());
				return;
			}
			if (nodeInfo.getClass() == tfg.app.model.entities.FundPort.class) {
				carteraMenu.show(this, evt.getX(), evt.getY());
				return;
			}

		}
	}

	// Actualizar del popupmenu de vl
	private void actuVlActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Borrar del popupmenu de vl
	private void borrarVlActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Anadir vl del popumpmenu de Fondo
	private void anadVlaFondoActionPerformed(java.awt.event.ActionEvent evt) {

		DefaultMutableTreeNode node = (DefaultMutableTreeNode) arbolFondos.getLastSelectedPathComponent();
		Object nodeInfo = node.getUserObject();

		FundDesc fundDesc = (FundDesc) nodeInfo;

		vlIsinIdLabel.setText(fundDesc.getfId());

		anadirVl.setVisible(true);

	}

	// Actualizar del popupmenu de Fondo
	private void actualizarFondoActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Borrar del popupmenu de Fondo
	private void borrarFondoActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Anadir fondo a cartera del popupmenu de cartera
	private void anFondoAcarteraActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Actualizar cartera del popupmenu de cartera
	private void actualizarCarteraActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Borrar cartera del popupmenu de cartera
	private void borrarCarteraActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	// Main de la app

	private static void createNodes(DefaultMutableTreeNode top) {

		DefaultMutableTreeNode found = null;
		DefaultMutableTreeNode porfolio = null;
		DefaultMutableTreeNode vl = null;

		List<FundPort> fundPorts = fundService.findAllFundPortfolios();

		for (int x = 0; x < fundPorts.size(); x++) {
			porfolio = new DefaultMutableTreeNode(fundPorts.get(x));
			top.add(porfolio);
			try {
				List<FundDesc> fundDescs = fundService.findFundsOfPortfolio(fundPorts.get(x));

				for (int x1 = 0; x1 < fundDescs.size(); x1++) {
					found = new DefaultMutableTreeNode(fundDescs.get(x1));
					porfolio.add(found);

					for (int x11 = 0; x11 < fundDescs.get(x1).getFundVls().size(); x11++) {
						vl = new DefaultMutableTreeNode(fundDescs.get(x1).getFundVls().get(x11));
						found.add(vl);

					}
				}
			} catch (InstanceNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}
	}

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		fundService = new FundServiceImpl();
		FundDesc fundDesc1 = new FundDesc("DE0008490962", "Pinball Wizards", "Alto riesgo", "Monetario", "Euro", 0.01,
				0.02);
		FundDesc fundDesc2 = new FundDesc("ES0173394034", "Pinball Wizards", "Alto riesgo", "Monetario", "Euro", 0.01,
				0.02);
		FundPort fundPort1 = new FundPort("Cartera Test 1", "Esto es una cartera de prueba");
		FundPort fundPort2 = new FundPort("Cartera Test 2", "Esto es una cartera de prueba");

		FundVl fundVl1 = new FundVl(LocalDate.parse("2020-04-20"), 25.00, fundDesc1);
		FundVl fundVl2 = new FundVl(LocalDate.parse("2020-04-21"), 25.00, fundDesc1);

		FundVl fundVl11 = new FundVl(LocalDate.parse("2020-04-20"), 25.00, fundDesc2);
		FundVl fundVl21 = new FundVl(LocalDate.parse("2020-04-22"), 25.00, fundDesc2);

		fundDesc1.getFundVls().add(fundVl1);
		fundDesc1.getFundVls().add(fundVl2);

		fundDesc2.getFundVls().add(fundVl11);
		fundDesc2.getFundVls().add(fundVl21);

		try {

			fundService.addFund(fundDesc1);
			fundService.addFund(fundDesc2);
			fundService.addFundPortfolio(fundPort1);
			fundService.addFundPortfolio(fundPort2);
			fundService.addPortDesc(fundPort1, fundDesc1);
			fundService.addPortDesc(fundPort1, fundDesc2);
			fundService.addPortDesc(fundPort2, fundDesc2);

		} catch (InputValidationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InstanceNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ui().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private static FundService fundService = null;
	private javax.swing.JMenuItem actuVl;
	private javax.swing.JMenuItem actualizarCartera;
	private javax.swing.JMenuItem actualizarFondo;
	private javax.swing.JMenuItem anFondoAcartera;
	private javax.swing.JButton anaCarteraBoton;
	private javax.swing.JButton anadFondoBoton;
	private javax.swing.JMenuItem anadVlaFondo;
	private javax.swing.JDialog anadirCartera;
	private javax.swing.JDialog anadirFondo;
	private javax.swing.JDialog anadirOp;
	private javax.swing.JDialog anadirVl;
	private javax.swing.JLabel apComLabel;
	private javax.swing.JFormattedTextField apComText;
	private javax.swing.JTree arbolFondos;
	private javax.swing.JMenuBar barraMenu;
	private javax.swing.JMenuItem borrarCartera;
	private javax.swing.JMenuItem borrarFondo;
	private javax.swing.JMenuItem borrarVl;
	private javax.swing.JMenuItem botonAnadirCartera;
	private javax.swing.JMenuItem botonAnadirFondo;
	private javax.swing.JLabel buscarLabel;
	private javax.swing.JTextField buscarText;
	private javax.swing.JButton canAnaCarteraBoton;
	private javax.swing.JButton canAnaFondoBoton;
	private javax.swing.JLabel cancelComLabel;
	private javax.swing.JFormattedTextField cancelComText;
	private javax.swing.JPopupMenu carteraMenu;
	private javax.swing.JLabel categoriaLabel;
	private javax.swing.JTextField categoriaText;
	private javax.swing.JLabel descCarteraLabel;
	private javax.swing.JTextArea descCarteraText;
	private javax.swing.JLabel divisaLabel;
	private javax.swing.JTextField divisaText;
	private javax.swing.JPopupMenu fondoMenu;
	private javax.swing.JLabel gestoraLabel;
	private javax.swing.JTextField gestoraText;
	private javax.swing.JLabel isinLabel;
	private javax.swing.JTextField isinText;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JLabel nomCarteraLabel;
	private javax.swing.JTextField nomCarteraText;
	private javax.swing.JButton opAccBoton;
	private javax.swing.JButton opCancBoton;
	private javax.swing.JLabel opCarteraLabel;
	private javax.swing.JLabel opFechaLabel;
	private javax.swing.JSpinner opFechaText;
	private javax.swing.JLabel opIsinLabel;
	private javax.swing.JLabel opOperacionLabel;
	private javax.swing.JFormattedTextField opOperacionText;
	private javax.swing.JLabel tipoLabel;
	private javax.swing.JTextField tipoText;
	private javax.swing.JButton vlAccBoton;
	private javax.swing.JButton vlCancBoton;
	private javax.swing.JLabel vlFechaLabel;
	private javax.swing.JSpinner vlFechaText;
	private javax.swing.JLabel vlIsinIdLabel;
	private javax.swing.JLabel vlIsinLabel;
	private javax.swing.JPopupMenu vlMenu;
	private javax.swing.JLabel vlVlLabel;
	private javax.swing.JFormattedTextField vlVlText;
	// End of variables declaration
}